### ISSUE TITLE
pyss3 now supports user-defined path

### ISSUE THREAD

**Issue by sergioburdisso** [LemurPwned/filmweb-nlp#2]
Hi @LemurPwned! I've just made some tiny updates on pyss3 taking into account your valuable feedback, now these lines: 

https://github.com/LemurPwned/filmweb-nlp/blob/58aad1700c4e2d86cd0c79b01c61c407812478f6/spacy-workflow/sentiment-spec/sentiment/sentiment.py#L8-L12

can be simply replaced by:

```python
clf = pyss3.SS3()
clf.load_model('/etc/cvoldata')
```

In addition, this line can be safely removed (by default pyss33 looks for a local "ss3_models" folder):
https://github.com/LemurPwned/filmweb-nlp/blob/3ea0ca0a67b0a167b9cc4cb75e2cfc8197bbdb0a/kubeflow-workflow/sentiment/sentiment.py#L8

If you want you can update pyss3 (``pip install --upgrade pyss3``) and try the new code, it will now make your code simpler and clearer. Sorry for not having taking this into account beforehand... PySS3 is a "baby" project in its 0.3 version (really far from a "1.0 version"), I know there's plenty of things to do, that's why I really appreciate your #comments, they helped me to improve the package and by doing that you also helped others using the package :) thanks, buddy!

The negative feedback is the best type of feedback because it is a "potential" improvement, so I really appreciate it. Next time do not hesitate to open an issue on the [repo](https://github.com/sergioburdisso/pyss3), any kind of help or feedback will be really appreciated.

Greets! take care and happy hacking :+1:

**Comment by LemurPwned** [comment]
Hi @sergioburdisso,
thanks so much! 
I am so sorry, I could've passed on my feedback in a more comprehensive way (also in a nicer way too)!
Thanks for giving me a heads up about the update, I'll incorporate that some time soon :)
